# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_song_playlist_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import db_func as db

class Ui_add_to_playlist_dialog(object):
    def setupUi(self, add_to_playlist_dialog):
        add_to_playlist_dialog.setObjectName("add_to_playlist_dialog")
        add_to_playlist_dialog.resize(400, 187)
        add_to_playlist_dialog.setStyleSheet("#add_to_playlist_dialog {\n"
"background-color: #212343;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(add_to_playlist_dialog)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(add_to_playlist_dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add.setStyleSheet("background-color: #A437E5;\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 15px;")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_cancel = QtWidgets.QPushButton(self.widget)
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel.setStyleSheet("background-color: #fff;\n"
"color: #A437E5;\n"
"border: none;\n"
"border-radius: 15px;")
        self.btn_cancel.setCheckable(True)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(add_to_playlist_dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #fff")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cbPLaylists = QtWidgets.QComboBox(add_to_playlist_dialog)
        self.cbPLaylists.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbPLaylists.setFont(font)
        self.cbPLaylists.setObjectName("cbPLaylists")
        self.gridLayout.addWidget(self.cbPLaylists, 1, 0, 1, 1)
        self.btn_cancel.toggled['bool'].connect(add_to_playlist_dialog.close)

        self.connection = db.connect_to_database()

        self.retranslateUi(add_to_playlist_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_to_playlist_dialog)

    def retranslateUi(self, add_to_playlist_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_to_playlist_dialog.setWindowTitle(_translate("add_to_playlist_dialog", "Thêm vào playlist"))
        self.btn_add.setText(_translate("add_to_playlist_dialog", "Thêm"))
        self.btn_cancel.setText(_translate("add_to_playlist_dialog", "Hủy"))
        self.label_2.setText(_translate("add_to_playlist_dialog", "Chọn playlist"))
        self.loadCbPlaylist()

    def loadCbPlaylist(self):
        playlists = db.load_playlists(self.connection)
        for p in playlists:
            self.cbPLaylists.addItem(f"{p.id} - {p.name}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_to_playlist_dialog = QtWidgets.QDialog()
    ui = Ui_add_to_playlist_dialog()
    ui.setupUi(add_to_playlist_dialog)
    add_to_playlist_dialog.show()
    sys.exit(app.exec_())
